[project]
name = "listen-to-wiki-changes"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.14",
    "httpx-sse>=0.4.1",
]

[tool.setuptools]
packages = ["l2wc_api"]
